name: Package with Gradle

on:
  push:
    tags: 
      - "*v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build JohnBase with Gradle and publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ github.token }}
      run: |
        ./gradlew :JohnBase:assembleRelease
        ./gradlew :JohnBase:publish
      if: contains(${{ github.ref_name }}, 'base-v')
    - name: Build JohnBaseCompose with Gradle and publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ github.token }}
      run: |
        ./gradlew :JohnBaseCompose:assembleRelease
        ./gradlew :JohnBaseCompose:publish
      if: contains(${{ github.ref_name }}, 'compose-v')