name: Package with Gradle

on:
  push:
    tags: 
      - "*v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
        echo 'triggered by ${{ github.ref_name }}'
        chmod +x gradlew
    - name: Build JohnBase with Gradle and publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ github.token }}
      run: |
        module=""
        if [[ "${{github.ref_name}}" == *"base-v"* ]]; then module=":JohnBase"; fi
        if [[ "${{github.ref_name}}" == *"compose-v"* ]]; then module=":JohnBaseCompose"; fi
        echo desire build module \'${module}\'
        if [ -z $module ]; then
          echo "module not determined, exit"
        else
          ./gradlew ${module}:assembleRelease
          ./gradlew ${module}:publish
        fi
