name: Package with Gradle

on:
  push:
    tags: 
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build john-base with Gradle
      run: ./gradlew :JohnBase:assembleRelease
    - name: Publish to GitHub
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ github.token }}
    - name: Build john-base-compose with Gradle
      run: ./gradlew :JohnBaseCompose:assembleRelease
    - name: Publish to GitHub
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ github.token }}
